default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :deploy do
    setup_ci

    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: Base64.decode64(ENV["ASC_KEY_CONTENT"]),
      is_key_content_base64: false
    )

    match(
      type: "appstore",
      app_identifier: "com.lightward",
      readonly: true,
      api_key: api_key,
      git_url: "git@github.com:lightward/apple-signing.git"
    )

    increment_build_number(
      build_number: ENV["BUILD_NUMBER"]
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: "49Q5LC84AR",
      profile_name: "match AppStore com.lightward",
      code_sign_identity: "Apple Distribution"
    )

    build_app(
      scheme: "Lightward",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
